package hibernate;
// Generated 24 nov. 2013 22:59:02 by Hibernate Tools 3.6.0



/**
 * Appareil generated by hbm2java
 */
public class Appareil  implements java.io.Serializable {


     private String idappareil;
     private Client client;
     private String numserieappareil;
     private byte[] historique;
     private String lienmanuel;

    public Appareil() {
    }

	
    public Appareil(String idappareil, String numserieappareil) {
        this.idappareil = idappareil;
        this.numserieappareil = numserieappareil;
    }
    public Appareil(String idappareil, Client client, String numserieappareil, byte[] historique, String lienmanuel) {
       this.idappareil = idappareil;
       this.client = client;
       this.numserieappareil = numserieappareil;
       this.historique = historique;
       this.lienmanuel = lienmanuel;
    }
   
    public String getIdappareil() {
        return this.idappareil;
    }
    
    public void setIdappareil(String idappareil) {
        this.idappareil = idappareil;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public String getNumserieappareil() {
        return this.numserieappareil;
    }
    
    public void setNumserieappareil(String numserieappareil) {
        this.numserieappareil = numserieappareil;
    }
    public byte[] getHistorique() {
        return this.historique;
    }
    
    public void setHistorique(byte[] historique) {
        this.historique = historique;
    }
    public String getLienmanuel() {
        return this.lienmanuel;
    }
    
    public void setLienmanuel(String lienmanuel) {
        this.lienmanuel = lienmanuel;
    }




}


