package hibernate;
// Generated 24 nov. 2013 22:59:02 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private String idclient;
     private String passwordclient;
     private String localisation;
     private Boolean disponibiliteclient;
     private Set appareils = new HashSet(0);

    public Client() {
    }

	
    public Client(String idclient, String passwordclient) {
        this.idclient = idclient;
        this.passwordclient = passwordclient;
    }
    public Client(String idclient, String passwordclient, String localisation, Boolean disponibiliteclient, Set appareils) {
       this.idclient = idclient;
       this.passwordclient = passwordclient;
       this.localisation = localisation;
       this.disponibiliteclient = disponibiliteclient;
       this.appareils = appareils;
    }
   
    public String getIdclient() {
        return this.idclient;
    }
    
    public void setIdclient(String idclient) {
        this.idclient = idclient;
    }
    public String getPasswordclient() {
        return this.passwordclient;
    }
    
    public void setPasswordclient(String passwordclient) {
        this.passwordclient = passwordclient;
    }
    public String getLocalisation() {
        return this.localisation;
    }
    
    public void setLocalisation(String localisation) {
        this.localisation = localisation;
    }
    public Boolean getDisponibiliteclient() {
        return this.disponibiliteclient;
    }
    
    public void setDisponibiliteclient(Boolean disponibiliteclient) {
        this.disponibiliteclient = disponibiliteclient;
    }
    public Set getAppareils() {
        return this.appareils;
    }
    
    public void setAppareils(Set appareils) {
        this.appareils = appareils;
    }




}


