package hibernate;
// Generated 24 nov. 2013 22:59:02 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Expert generated by hbm2java
 */
public class Expert  implements java.io.Serializable {


     private String idexpert;
     private String expertpwd;
     private String localisationexpert;
     private Boolean disponibiliteexpert;
     private Set pannes = new HashSet(0);

    public Expert() {
    }

	
    public Expert(String idexpert) {
        this.idexpert = idexpert;
    }
    public Expert(String idexpert, String expertpwd, String localisationexpert, Boolean disponibiliteexpert, Set pannes) {
       this.idexpert = idexpert;
       this.expertpwd = expertpwd;
       this.localisationexpert = localisationexpert;
       this.disponibiliteexpert = disponibiliteexpert;
       this.pannes = pannes;
    }
   
    public String getIdexpert() {
        return this.idexpert;
    }
    
    public void setIdexpert(String idexpert) {
        this.idexpert = idexpert;
    }
    public String getExpertpwd() {
        return this.expertpwd;
    }
    
    public void setExpertpwd(String expertpwd) {
        this.expertpwd = expertpwd;
    }
    public String getLocalisationexpert() {
        return this.localisationexpert;
    }
    
    public void setLocalisationexpert(String localisationexpert) {
        this.localisationexpert = localisationexpert;
    }
    public Boolean getDisponibiliteexpert() {
        return this.disponibiliteexpert;
    }
    
    public void setDisponibiliteexpert(Boolean disponibiliteexpert) {
        this.disponibiliteexpert = disponibiliteexpert;
    }
    public Set getPannes() {
        return this.pannes;
    }
    
    public void setPannes(Set pannes) {
        this.pannes = pannes;
    }




}


