package hibernate;
// Generated 24 nov. 2013 22:59:02 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Panne generated by hbm2java
 */
public class Panne  implements java.io.Serializable {


     private int idpanne;
     private String pannedescription;
     private Set experts = new HashSet(0);

    public Panne() {
    }

	
    public Panne(int idpanne) {
        this.idpanne = idpanne;
    }
    public Panne(int idpanne, String pannedescription, Set experts) {
       this.idpanne = idpanne;
       this.pannedescription = pannedescription;
       this.experts = experts;
    }
   
    public int getIdpanne() {
        return this.idpanne;
    }
    
    public void setIdpanne(int idpanne) {
        this.idpanne = idpanne;
    }
    public String getPannedescription() {
        return this.pannedescription;
    }
    
    public void setPannedescription(String pannedescription) {
        this.pannedescription = pannedescription;
    }
    public Set getExperts() {
        return this.experts;
    }
    
    public void setExperts(Set experts) {
        this.experts = experts;
    }




}


